### ISSUE TITLE
Error when the popover is inside a tab on Android

### ISSUE THREAD

**Issue by fmendoza** [skypanther/AlloyPopover#3]
Hi, on iOS this works perfectly, but on android, it throws "Error: cannot add window/tabgroup to another window/tabgroup"

Any solution to this?

**Comment by skypanther** [comment]
I thought I had reworked this to use a Ti.UI.View rather than Window. Maybe just in a local copy. I'll see what I can find and get posted for you. Thanks for letting me know.

**Comment by fmendoza** [comment]
Thank you @skypanther

**Comment by skypanther** [comment]
I uploaded a new version that in my testing works on Android within tabs. I can't use a View after all. So, it's set to use a modal window. Depending on your Android version and theme, there might be some issues (like a title bar showing up). You can modify the TSS to set navBarHidden on #popover if this is the case.

**Comment by fmendoza** [comment]
Thanks!!! :+1:
